spring.application.name=Random-Email-Generator

server.port=8081

spring.mail.username=root
spring.datasource.url=jdbc:mysql://localhost:3306/random_email_generator
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.mail.password=SJ8W@vWN


