package com.randomEmailGenerator.util;

import java.util.Arrays;
import java.util.List;

public class Names {

    public static List<String> PAKISTANI_BOYS_NAMES = Arrays.asList(
            "Ahmad", "Ali", "Abdullah", "Abdul", "Ahsan", "Arham", "Asad", "Ayan", "Bilal", "Danish",
            "Ehsan", "Fahad", "Farhan", "Hamza", "Haris", "Hassan", "Hussain", "Ibrahim", "Imran", "Irfan",
            "Junaid", "Kamran", "Kashif", "Majid", "Nadeem", "Nasir", "Omar", "Qasim", "Rashid",
            "Saad", "Saeed","Farhad","Salman", "Shahid", "Tariq", "Usman", "Waqas", "Yasir", "Zain", "Zubair",
            "Aamir", "Adnan", "Akbar", "Akram", "Altaf", "Ameer", "Amir", "Anwar", "Arsalan", "Asif",
            "Asim", "Atif", "Azhar", "Aziz", "Badar", "Basit", "Faisal", "Faizan", "Faraz", "Furqan",
            "Ghulam", "Haider", "Hamid", "Hammad", "Haseeb", "Hatim", "Iftikhar", "Ismail", "Jameel", "Javed",
            "Jawad", "Kabir", "Khalid", "Luqman", "Mahmood", "Malik", "Mansoor", "Mehboob", "Mehmood", "Mirza",
            "Moin", "Mudassir", "Muneeb", "Mushtaq", "Mustafa", "Naeem", "Najeeb", "Naveed", "Noman",
            "Noor", "Nouman", "Pervaiz", "Qaiser", "Qamar", "Raheel", "Raja", "Rameez", "Rehan", "Rizwan",
            "Sabir", "Sajid", "Salam", "Saleem", "Samad", "Sameer", "Sami", "Shoaib", "Sikander", "Sohail",
            "Subhan", "Sufyan", "Suleman", "Tahir", "Talha", "Tanveer", "Tauseef", "Ubaid", "Umar", "Umer",
            "Umair", "Usama", "Wahab", "Waseem", "Younis", "Yousuf", "Zafar", "Zaheer", "Zahid", "Zeeshan",
            "Aariz", "Aashir", "Abid", "Adeel", "Adil", "Afzal", "Aizaz", "Aman", "Amin", "Anas",
            "Anjum", "Arbab", "Arif", "Ashraf", "Aslam", "Aun", "Awais", "Ayaz", "Ayyub", "Azam",
            "Azmat", "Babar", "Bakhtawar", "Baqir", "Barakat", "Basharat", "Bashir", "Bilawal", "Burhan", "Chaudhry",
            "Dawood", "Danyal", "Daoud", "Dilawar", "Eman", "Faham", "Fahd", "Fakhir", "Fareed", "Farman",
            "Fateh", "Fawad", "Fayaz", "Feroz", "Fizan", "Ghalib", "Ghazi", "Gohar", "Gul", "Gulzar",
            "Habib", "Hadi", "Hafeez", "Hakim", "Halim", "Hanif", "Hanzala", "Hashim", "Hayat", "Hidayat",
            "Hikmat", "Hilal", "Humaid", "Huraira", "Ibad", "Ijlal", "Ilyas", "Imad", "Intizar", "Iqbal",
            "Irshad", "Isa", "Ishaq", "Israr", "Izzat", "Jabbar", "Jafar", "Jahan", "Jalal", "Jamshed",
            "Jasim", "Jawed", "Jibran", "Kaif", "Kamal", "Karar", "Karam", "Kareem", "Kashan", "Kashmiri",
            "Kazim", "Khaleel", "Khalil", "Khan", "Khizar", "Khurram", "Khwaja", "Kifayat", "Latif", "Liaqat",
            "Madni", "Mahad", "Mahdi", "Maher", "Mahfooz", "Mahr", "Mansur", "Maroof", "Masood", "Mateen",
            "Mazhar", "Mazin", "Miftah", "Minhaj", "Miraj", "Mishal", "Mobeen", "Momin", "Muaaz", "Mubarak",
            "Mudasir", "Mueed", "Mujahid", "Mujtaba", "Mukaram", "Mukhtar", "Muneer", "Munir", "Murtaza", "Musa",
            "Nadir", "Nafees", "Nageen", "Nahyan", "Najam", "Naji", "Najib", "Naseeb", "Nasim", "Natiq",
            "Nawab", "Nawaz", "Nazakat", "Nazim", "Nazir", "Nuh", "Numan", "Obaid", "Osama", "Parvez",
            "Qadeer", "Qadir", "Qais", "Qalandar", "Qayyum", "Qudrat", "Qutub", "Rafi", "Rafiq", "Rahat",
            "Rahil", "Rahman", "Raihan", "Rais", "Ramiz", "Rashad", "Rauf", "Rayyan", "Raza", "Rehman",
            "Riaz", "Rida", "Rifat", "Rohail", "Rukan", "Rushdi", "Saadat", "Sabri", "Sadat", "Sadiq",
            "Safdar", "Safi", "Sahil", "Salah", "Saleh", "Salik", "Samar", "Samiullah", "Saqib", "Sarwar",
            "Satwat", "Saud", "Shabaz", "Shafeeq", "Shafiq", "Shahjahan", "Shahmir", "Shahryar", "Shahzad", "Shaikh",
            "Shakeel", "Shakil", "Shakir", "Shams", "Sharaf", "Sharif", "Shaukat", "Shayan", "Sheharyar", "Shehroz",
            "Shibli", "Shiraz", "Shuaib", "Siddiq", "Siraj", "Sohrab", "Sufi", "Suhail", "Sulaiman", "Sultan",
            "Suroor", "Taha", "Taimoor", "Talal", "Tamoor", "Taqi", "Tasleem", "Tauqeer", "Tayyab", "Tayyib",
            "Tufail", "Ubaid", "Uthman", "Wahaj", "Wajahat", "Wajid", "Wali", "Waqar", "Wasif", "Wazir",
            "Yahya", "Yamin", "Yaqoob", "Yasin", "Yousaf", "Yusha", "Zafar", "Zahoor", "Zaid", "Zaki",
            "Zaman", "Zameer", "Zarar", "Zawar", "Zayd", "Zia", "Zohaib", "Zuhair", "Zulqarnain", "Zunair",
            "Zuraiz", "Aaban", "Aabid", "Aadil", "Aafaq", "Aalam", "Aalee", "Aalim", "Aaqib", "Aarif",
            "Aatif", "Aazam", "Abbas", "Abir", "Abraar", "Abu", "Abyan", "Adam", "Adeeb",
            "Adham", "Affan", "Afnan", "Aftab", "Ahad", "Ahmar", "Ahtasham", "Ahyan", "Ajmal", "Akif",
            "Alam", "Alauddin", "Aleem", "Alyan", "Amaan", "Amaar", "Ammer", "Amyn", "Anay", "Andaleeb",
            "Aniq", "Anis", "Annas", "Aqdas", "Aqeel", "Aqib", "Arafat", "Arbaaz", "Ariyan", "Arish",
            "Armaan", "Arshad", "Arshalan", "Arslan", "Aryan", "Asfand", "Asghar", "Ashaz", "Asher", "Ashfaq",
            "Ashir", "Ashmal", "Ashrif", "Asrar", "Ata", "Azad", "Azan", "Azlan", "Azzam", "Baahir",
            "Badr", "Bahaar", "Bahadur", "Bakhtiar", "Bakhtiyar", "Bakr", "Baqar", "Barak", "Barkat", "Basheer",
            "Basim", "Bassam", "Binyamin", "Chand", "Daaniyal", "Dabeer", "Dara", "Dawoud", "Dawud", "Dayyan",
            "Dildar", "Diyan", "Ebad", "Ebrahim", "Eesa", "Ejaz", "Elham", "Emad", "Eshan", "Essa",
            "Faaiz", "Faakhir", "Faateh", "Fadi", "Faheem", "Fahmi", "Fakhar", "Fakhr", "Falah", "Faras",
            "Fardeen", "Farid", "Faris", "Faruq", "Fateen", "Fawaz", "Fawzi", "Faysal", "Fazal", "Fida",
            "Firas", "Fuaad", "Ghaazi", "Ghani", "Ghaus", "Ghufran", "Haadi", "Haafiz", "Haamid", "Haani",
            "Haarith", "Haashim", "Habeeb", "Hafs","Hafsa", "Hassam", "Hussam", "Hussayn", "Huzaifah", "Huzayfah", "Ibraheem",
            "Ibtisam", "Idrees", "Idris", "Ifham", "Ifran", "Imaad", "Imam", "Imdad", "Imtiaz", "Inaam",
            "Inayat", "Intekhab", "Irtaza", "Irteza", "Irtiza", "Ishfaq", "Ishtiaq", "Islah", "Ismat", "Iyaad",
            "Izaan", "Izaat", "Izhar", "Jaad", "Jabir", "Jaffer", "Jahanzaib", "Jahangir", "Jalees", "Jamaal",
            "Jarrah", "Jasam", "Jasir", "Jaudat", "Jawhar", "Jawwad", "Jazib", "Jihad", "Jiya", "Jubair",
            "Juwairiyah", "Kaamil", "Kaashif", "Kafeel", "Kaleem", "Kameel", "Karam", "Kasim", "Khaldun", "Khalis",
            "Khayr", "Khubaib", "Khuzaima", "Kinza", "Kumail", "Laeeq", "Laiq", "Luqmaan", "Maaz", "Maisam",
            "Makki", "Mamoon", "Manzoor", "Marwan", "Masroor", "Mawdood", "Mehran", "Miskeen", "Mufaddal", "Mufeed",
            "Muhsin", "Muntasir", "Muqaddas", "Murad", "Mursaleen", "Musab", "Musaddiq", "Mustafeez", "Mutahhar", "Mutasim",
            "Mutasir", "Muzammil", "Nabeel", "Nadhir", "Nafis", "Najm", "Naseem", "Naseer", "Navid", "Nihal",
            "Nisar", "Nur", "Nuruddin", "Omair", "Osaid", "Othman", "Owais", "Qaabil", "Qadir", "Qaaim",
            "Qabeel", "Qadar", "Qasu", "Qudamah", "Quraish", "Qusay", "Raad", "Raafe", "Raahil", "Raamiz",
            "Raaid", "Raashid", "Rab", "Rabah", "Rabi", "Rabih", "Rafay", "Rafe", "Rafee", "Raghib",
            "Rai", "Rajab", "Ramadan", "Rami", "Ramzan","Rashid", "Rasheed", "Rauoof","Rauf", "Razzaq", "Rehaan",
            "Ridwan", "Rifaah", "Rohaan", "Rustam", "Saabir", "Saadiq", "Saahib", "Sajid", "Saalih", "Saalim",
            "Saami", "Saamir","Sameer", "Saba", "Sabah", "Sabeeh", "Sachal", "Sadaqat", "Sadeed", "Sadeeq", "Sadik",
            "Sahban", "Saheel","Sahil", "Sajawal", "Sakhi", "Salaar", "Sallam", "Samaad", "Saqr", "Sarim", "Sarmad",
            "Sawal", "Saif", "Sayyid", "Shaheed", "Shahriyar", "Shahzaib", "Shakoor", "Shan", "Shareef", "Shariq",
            "Shayaan", "Shujaat", "Shukri", "Zaaheer", "Zaahid", "Zaahir", "Zaaim", "Zafir", "Zakwan", "Zulfiqar","Sheikh","Butt","Jutt","Cheema","Chaudary","Rao","Sandhu"
    );

    public static List<String> PAKISTANI_GIRLS_NAMES = Arrays.asList(
            "Aalia", "Aamina", "Aaniya", "Aasia", "Abeera", "Abida", "Adina", "Afifa", "Afnan", "Afsa",
            "Aisha", "Aleena", "Alia", "Alina", "Aliza", "Alya", "Aman", "Amani", "Amara", "Amber",
            "Ameena", "Amina", "Amna", "Anam", "Anaya", "Anila", "Anum", "Areeba", "Areesha", "Arfa",
            "Arisha", "Arzoo", "Asma", "Atiya", "Ayesha", "Ayla", "Azka", "Azra", "Bakhtawar", "Bareera",
            "Barkat", "Bushra", "Dania", "Dua", "Eman", "Erum", "Fajr", "Falak", "Farah", "Farhana",
            "Farida", "Farwa","Fauzia", "Fiza", "Fizza", "Ghazala", "Gul", "Gulnar", "Habiba",
            "Hadia", "Hafsa", "Hajra", "Haleema", "Halima", "Hamna", "Hania", "Hareem", "Hasanat", "Haseena",
            "Hiba", "Hina", "Hira", "Hoorain", "Huda", "Huma", "Humaira", "Hurriya", "Husna", "Iffat",
            "Iman", "Inaya", "Iqra", "Iram", "Irsa", "Isha", "Ishrat", "Isra", "Izza", "Jannat",
            "Javeria", "Jiya", "Kainat", "Kalsoom", "Kashaf", "Kashmala", "Kausar", "Khalida", "Kiran",
            "Kulsoom", "Laiba", "Laraib", "Latafat", "Layla", "Madiha", "Maham", "Mahira", "Mahjabeen", "Mahum",
            "Maida", "Maira", "Maisha", "Malaika", "Malika", "Mansha", "Maria", "Marwa", "Mashal", "Masuma",
            "Mehak", "Mehreen", "Mehwish", "Mehza", "Minal", "Minahil", "Misbah", "Momina", "Mubina", "Muneeba",
            "Musfira", "Muskan", "Nadia", "Nafisa", "Nageen", "Najma", "Nargis", "Nasreen", "Nawal", "Nazia",
            "Nida", "Nimra", "Noor", "Noreen", "Nudrat", "Nusrat", "Palwasha", "Parveen", "Qudsia", "Rabia",
            "Rafia", "Rahima", "Rameen", "Ramsha", "Rani", "Rashida", "Reema", "Rehana", "Rida", "Rimsha",
            "Romana", "Rukhsar", "Rumana", "Ruqayya", "Saba", "Sabah", "Sabeen", "Sabiha", "Sadaf", "Sadia",
            "Safiya", "Sahar", "Saima", "Saira", "Sajida", "Sakina", "Salma", "Samar", "Sameen", "Samiya",
            "Samra", "Sana", "Sanam", "Sania", "Sara", "Sarah", "Sawera", "Seema", "Sehar", "Sehrish",
            "Seshat", "Shabana", "Shabnam", "Shagufta", "Shaheen", "Shahida", "Shahnaz", "Shaista", "Shakeela", "Shamim",
            "Shamsha", "Shanza", "Shazia", "Sheeba", "Shehla", "Shehrbano", "Sheza", "Shireen", "Shiza", "Shumaila",
            "Sidra", "Sobia", "Sonia", "Suhana", "Sumbal", "Sumera", "Sumaira", "Sumayya", "Sundas", "Tabinda",
            "Tabassum", "Tahira", "Tahreem", "Taj", "Talat", "Tamanna", "Tania", "Taqdees", "Taskeen", "Tasneem",
            "Tayyaba", "Tehmina", "Ujala", "Urooj", "Uzma", "Varda", "Wajeeha", "Warda", "Yasmeen", "Yumna",
            "Zahida", "Zahra", "Zainab", "Zara", "Zareen", "Zarmina", "Zartaj", "Zeenat", "Zoha", "Zohra",
            "Zonaira", "Zoya", "Zubaira", "Zulekha", "Aaliyah", "Aamna", "Aara", "Abeer", "Adab", "Adara",
            "Adeela", "Afia", "Afra", "Afsheen", "Aida", "Aila", "Aiman", "Aina", "Aira", "Aiza",
            "Aizah", "Aleezay", "Alif", "Alishba", "Almas", "Alvina", "Alyah", "Alyza", "Amal", "Amaya",
            "Ambreen", "Ameerah", "Amel", "Amirah", "Amtul", "Anabia", "Andaleeb", "Aniqa", "Anisa", "Anisha",
            "Anmol", "Anoosha", "Anushka", "Aqsa", "Areej", "Arwa", "Arya", "Asbah", "Asfoora", "Ashna",
            "Asifa", "Asiya", "Atiqa", "Azalea", "Aziza", "Bano", "Bareerah", "Basant", "Batool", "Bazgha",
            "Beesha", "Benazir", "Bisma", "Chanda", "Daniya", "Durdana", "Eesha", "Fahmida", "Faiza", "Fajar",
            "Fara", "Farhat", "Fatema", "Fozia", "Ghania", "Ghazal", "Gulbahar", "Gulnaz", "Hamida", "Hana",
            "Haniya", "Hoor", "Hurriya", "Inaaya", "Inayat", "Ismat", "Jahan", "Jahanara", "Kainaat", "Kashf",
            "Komal", "Lata", "Madihah", "Maham", "Mahgul", "Mahin", "Mahpara", "Mahrukh", "Mahwish", "Maizah",
            "Malalai", "Maliha", "Mariam", "Marzia", "Mashooq", "Masira", "Masooma", "Meharban", "Meher", "Mehnaz",
            "Mehr", "Mehrun", "Misha", "Mishal", "Komal", "Mushk", "Nabeeha", "Nabila", "Nageena", "Nahla",
            "Najia", "Najiba", "Najma", "Naseema", "Nashit", "Nashita", "Nasim", "Nasira", "Natasha", "Naveera",
            "Naveen", "Nayab", "Nayyab", "Naz", "Nazakat", "Nazeefa", "Nazia", "Nazish", "Nazli", "Neelam",
            "Neelofar", "Nigar", "Nilofer", "Nimrah", "Noor", "Noor", "Noorjahan", "Noreen", "Noshaba", "Nuzhat",
            "Palwasha", "Parisa", "Parizad", "Pashmina", "Pervin", "Qamar", "Qirat", "Qudsia", "Rabail", "Rabia",
            "Rafia", "Rahat", "Rahila", "Rahima", "Raheela", "Raihana", "Raisa", "Rameen", "Ramish", "Ramsha",
            "Rangila", "Rani", "Rashida", "Rasoolan", "Razia", "Rehana", "Rehmat", "Resham", "Riffat", "Rukhsana",
            "Rukhsar", "Rumana", "Ruqaiya", "Sabahat", "Sabeeha", "Sabiha", "Sadaqat", "Sadiqa", "Safia", "Sahar",
            "Sahira", "Saima", "Saira", "Sajida", "Sakina", "Saliha", "Salima", "Samar", "Sameera", "Samina",
            "Samra", "Sana", "Sanam", "Sania", "Saniya", "Sara", "Sarah", "Sarwat", "Sawera", "Seema",
            "Sehar", "Sehrish", "Shabana", "Shabnam", "Shagufta", "Shaheen", "Shahida", "Shahnaz", "Shaista", "Shakeela",
            "Shamim", "Shamim", "Shamsha", "Shanza", "Shazia", "Sheeba", "Shehla", "Shehnaz", "Shehreen",
            "Shehryar", "Shehzadi", "Sherbano", "Sheri", "Sherin", "Sheza", "Shireen", "Shiza", "Shumaila",
            "Sidra", "Sobia", "Sonia", "Suboohi", "Sughra", "Suhana", "Suhra", "Sukaina", "Sukayna", "Sultana",
            "Sumaira", "Sumayya", "Sumbul", "Sundas", "Tabassum", "Tahira", "Tahira", "Tahreem", "Taj", "Talat",
            "Tamanna", "Tania", "Taqdees", "Taskeen", "Tasneem", "Tayyaba", "Tehmina", "Ujala", "Urooj", "Uzma",
            "Varda", "Wajeeha", "Warda", "Yasmeen", "Yumna", "Zahida", "Zahra", "Zainab", "Zara", "Zareen",
            "Zarmina", "Zartaj", "Zeenat", "Zoha", "Zohra", "Zonaira", "Zubaira", "Zulekha", "Zunaira"
            ,"Sheikh","Butt","Jutt","Cheema","Chaudary","Rao","Sandhu","Randhawa"
    );

    public static List<String> INDIAN_BOYS_NAMES = Arrays.asList(
            "Aarav", "Aarush", "Aayush", "Abhinav", "Aditya", "Akshay", "Aman", "Amit", "Aniket", "Anirudh",
            "Ankit", "Anuj", "Anupam", "Arjun", "Arnav", "Arun", "Ashish", "Ashok", "Avinash", "Ayush",
            "Bharat", "Bhaskar", "Brijesh", "Chandan", "Chirag", "Daksh", "Deepak", "Dev", "Dhanush", "Dhruv",
            "Dinesh", "Divyansh", "Gaurav", "Gautam", "Girish", "Gopal", "Harsh", "Harshit", "Hemant", "Himanshu",
            "Hitesh", "Ishaan", "Jatin", "Jay", "Jayesh", "Kabir", "Karan", "Kartik", "Keshav", "Krish",
            "Krishna", "Kunal", "Laksh", "Lakshay", "Lokesh", "Madhav", "Manish", "Mayank", "Mohit", "Nakul",
            "Naman", "Naveen", "Nikhil", "Niraj", "Nishant", "Om", "Parth", "Pranav", "Pratham", "Prateek",
            "Praveen", "Raghav", "Rahul", "Raj", "Rajan", "Rajesh", "Rakesh", "Raman", "Ramesh", "Ranbir",
            "Rishabh", "Rishi", "Ritesh", "Rohan", "Rohit", "Ronak", "Sachin", "Sagar", "Sahil", "Samar",
            "Sanjay", "Saurabh", "Shiv", "Shivam", "Shubham", "Siddharth", "Soham", "Somesh", "Sourav", "Suresh",
            "Surya", "Tanmay", "Tarun", "Uday", "Ujjwal", "Utkarsh", "Vaibhav", "Varun", "Ved", "Vedant",
            "Vicky", "Vihan", "Vikram", "Vikrant", "Vimal", "Vinay", "Vineet", "Vinit", "Vipul", "Viraj",
            "Vishal", "Vivek", "Yash", "Yogesh", "Yuvraj", "Aadarsh", "Aadi", "Aadit", "Aadvik", "Aahan",
            "Aarush", "Aayansh", "Abhimanyu", "Advaith", "Advait", "Advay", "Agastya", "Akshaj", "Akshat", "Amol",
            "Anay", "Ansh", "Anshuman", "Arinjay", "Arpit", "Arshit", "Aryaman", "Atharv", "Atul", "Avyan",
            "Ayushman", "Badal", "Bhavya", "Bodhi", "Chaitanya", "Charak", "Darsh", "Darshit", "Devansh", "Dhananjay",
            "Dhairya", "Dhvanit", "Divit", "Divyanshu", "Dwij", "Ehsaan", "Ekanth", "Eklavya", "Faiyaz", "Farhan",
            "Gatik", "Gauransh", "Gunjan", "Hredhaan", "Hridaan", "Hridhay", "Ishwar", "Ivaan", "Jai", "Jayan",
            "Jayant", "Jaydeep", "Jayesh", "Jignesh", "Kailash", "Kalpit", "Keyur", "Kiaan", "Krishiv", "Krisha",
            "Krishav", "Kush", "Kushagra", "Kyra", "Lakshit", "Lavish", "Luv", "Madhav", "Madhup", "Manan",
            "Manas", "Mihir", "Mitesh", "Moksh", "Nachiket", "Naksh", "Naman", "Nand", "Navodit", "Nihal",
            "Nimit", "Nirvaan", "Nishith", "Ojas", "Omkar", "Onkar", "Parixit", "Parthiv", "Pranay", "Pranit",
            "Pranshu", "Pratyush", "Prayag", "Prem", "Prithvi", "Priyansh", "Purab", "Purushottam", "Raghavendra", "Rajan",
            "Reyansh", "Rishit", "Ritvik", "Rudra", "Rudransh", "Rugved", "Rupak", "Saatvik", "Saharsh", "Saksham",
            "Samarth", "Sambhav", "Sameer", "Sarthak", "Shakti", "Shivansh", "Shlok", "Shrey", "Shreyas", "Shubh",
            "Siddh", "Smaran", "Sohum", "Srijan", "Suryansh", "Suvan", "Swastik", "Tanuj", "Tanish", "Tejas",
            "Tushar", "Udit", "Umang", "Utsav", "Vansh", "Varad", "Vedang", "Veer", "Vidur", "Vihaan",
            "Viraat", "Vishnu", "Yug", "Yuvan", "Yuvraj", "Zain", "Zeeshan", "Aarush", "Aayush", "Abhay",
            "Abhiram", "Advaith", "Advik", "Agastya", "Akshath", "Amartya", "Anay", "Anmol", "Anshul", "Arin",
            "Arsh", "Arya", "Atharva", "Ayaan", "Ayansh", "Ayush", "Bhavik", "Bhavya", "Bhuvan", "Chaitanya",
            "Chand", "Darsh", "Devang", "Dhanush", "Dhruva", "Divij", "Divyansh", "Dwij", "Eeshan", "Ehan",
            "Eshaan", "Farhan", "Gagan", "Gatik", "Gaurang", "Gautam", "Harsh", "Harshul", "Himanshu", "Hredhaan",
            "Ishaan", "Ishwar", "Jai", "Jay", "Jayant", "Jayesh", "Jignesh", "Kabir", "Kailash", "Kartik",
            "Keyur", "Kiaan", "Krish", "Krishiv", "Krishna", "Kush", "Laksh", "Lakshya", "Luv", "Madhav",
            "Manan", "Manas", "Mayank", "Mihir", "Mitesh", "Moksh", "Nachiket", "Nakul", "Naman", "Nand",
            "Navodit", "Nihal", "Nimit", "Nirvaan", "Nishant", "Ojas", "Om", "Omkar", "Onkar", "Parixit",
            "Parth", "Parthiv", "Pranav", "Pranay", "Pranit", "Pranshu", "Pratyush", "Prayag", "Prem", "Prithvi",
            "Priyansh", "Purab", "Purushottam", "Raghav", "Rajan", "Reyansh", "Rishabh", "Rishit", "Ritvik", "Rudra",
            "Rudransh", "Rugved", "Rupak", "Saatvik", "Saharsh", "Saksham", "Samarth", "Sambhav", "Sameer", "Sarthak",
            "Shakti", "Shiv", "Shivansh", "Shlok", "Shrey", "Shreyas", "Shubh", "Siddh", "Smaran", "Soham",
            "Srijan", "Surya", "Suvan", "Swastik", "Tanuj", "Tanish", "Tejas", "Tushar", "Udit", "Umang",
            "Utsav", "Vansh", "Varad", "Vedang", "Veer", "Vidur", "Vihaan", "Viraat", "Vishnu", "Yug",
            "Yuvan", "Yuvraj", "Zain", "Zeeshan"
    );

    public static List<String> INDIAN_GIRLS_NAMES = Arrays.asList(
            "Aahana", "Aanya", "Aaradhya", "Aarohi", "Aashi", "Aashna", "Aastha", "Aditi", "Advika", "Agrima",
            "Ahana", "Aishwarya", "Akanksha", "Akshara", "Alia", "Alisha", "Amaira", "Amaya", "Amrita", "Ananya",
            "Anaya", "Anika", "Anisha", "Anjali", "Anvi", "Anya", "Aparna", "Archana", "Arpita", "Arya",
            "Asha", "Ashna", "Avani", "Avantika", "Ayushi", "Bhavya", "Bhumika", "Bipasha", "Charu", "Chhavi",
            "Daksha", "Damini", "Deepika", "Devika", "Dhara", "Dhriti", "Dia", "Diya", "Divya", "Esha",
            "Eva", "Gargi", "Garima", "Gayatri", "Geet", "Geetika", "Gia", "Gitanjali", "Grishma", "Hansika",
            "Harshita", "Heer", "Hema", "Himani", "Hina", "Ira", "Ishani", "Ishita", "Jahnvi", "Jaya",
            "Jhanvi", "Jiya", "Kajal", "Kalyani", "Kanika", "Kashish", "Kavya", "Khushi", "Kiara", "Kirti",
            "Komal", "Kriti", "Kritika", "Krithika", "Lakshmi", "Lavanya", "Liya", "Madhavi", "Mahi", "Mahika",
            "Maitri", "Manisha", "Manyata", "Meera", "Megha", "Meghna", "Misha", "Mitali", "Mohan", "Moksha",
            "Mridula", "Muskan", "Myra", "Naisha", "Naina", "Navya", "Neha", "Nidhi", "Niharika", "Nikita",
            "Nisha", "Nitya", "Ojasvi", "Palak", "Pari", "Paridhi", "Parineeti", "Pihu", "Pooja", "Pragya",
            "Prachi", "Pratibha", "Pratiksha", "Preeti", "Priya", "Priyanka", "Radha", "Ragini", "Rani", "Rashi",
            "Rati", "Raveena", "Reema", "Reena", "Ria", "Riddhi", "Rishika", "Ritika", "Riya", "Roshni",
            "Ruchi", "Rukmini", "Rupal", "Saanvi", "Sadhna", "Sakshi", "Samaira", "Samiksha", "Sana", "Sanjana",
            "Sanskriti", "Sanya", "Sarika", "Sejal", "Shalini", "Shanaya", "Shanti", "Shivani", "Shreya", "Shrishti",
            "Shruti", "Shweta", "Simran", "Sita", "Sneha", "Sonal", "Sonali", "Sonam", "Srishti", "Stuti",
            "Suhana", "Sumati", "Sunita", "Surbhi", "Swara", "Swati", "Tanvi", "Tanya", "Tara", "Trisha",
            "Tulsi", "Twinkle", "Ujjwala", "Urvi", "Vaani", "Vaidehi", "Vani", "Vanshika", "Varsha", "Vedika",
            "Vidhi", "Vidya", "Vrinda", "Yamini", "Yashasvi", "Yashika", "Yashvi", "Yasti", "Zara", "Zoya",
            "Aadya", "Aanya", "Aarushi", "Aashi", "Aayat", "Adhira", "Adya", "Akanksha", "Akshita", "Alina",
            "Amaira", "Amoli", "Anagha", "Anahita", "Anamika", "Ananya", "Anaya", "Anika", "Anisha", "Anjali",
            "Anvi", "Anya", "Aparajita", "Archita", "Aruna", "Aryahi", "Asmita", "Avani", "Avanti", "Ayana",
            "Bageshri", "Bansari", "Barsha", "Bela", "Bhadra", "Bhavika", "Bhoomi", "Bhumika", "Bipasha", "Chandni",
            "Charvi", "Chhaya", "Daksha", "Damini", "Darshana", "Deeksha", "Deepali", "Devanshi", "Dhara", "Dhatri",
            "Dhwani", "Dia", "Diksha", "Divija", "Divyanshi", "Drishti", "Ela", "Eshana", "Falguni", "Gargi",
            "Gaurangi", "Gayatri", "Gunjan", "Hansika", "Harinya", "Harsha", "Harshita", "Heer", "Hetal", "Himadri",
            "Hiral", "Iha", "Iksha", "Ila", "Indira", "Ira", "Ishani", "Ishita", "Jagriti", "Jahnvi",
            "Jaya", "Jhanvi", "Jigyasa", "Jivika", "Kajal", "Kalpana", "Kamakshi", "Kanak", "Kanika", "Kashvi",
            "Kavisha", "Khushi", "Kiara", "Kirti", "Komal", "Krishika", "Kriti", "Kritika", "Krithika", "Kyra",
            "Lakshita", "Lavanya", "Lipika", "Madhavi", "Mahika", "Maitreyi", "Manjari", "Manvi", "Manyata", "Meenakshi",
            "Meghana", "Misha", "Mitali", "Mohini", "Moksha", "Mridula", "Mrunal", "Muskan", "Myra", "Naina",
            "Nakshatra", "Nandini", "Navya", "Neelam", "Nehal", "Nidhi", "Niharika", "Nikita", "Nimisha", "Nirali",
            "Nisha", "Nishita", "Nitya", "Ojasvi", "Palak", "Pari", "Parineeti", "Pihu", "Pooja", "Pragati",
            "Pragya", "Prachi", "Pratiksha", "Preeti", "Prisha", "Priya", "Priyal", "Priyanka", "Radhika", "Ragini",
            "Rajvi", "Rashi", "Rati", "Reeva", "Rehnuma", "Ria", "Riddhi", "Rishika", "Ritika", "Riya",
            "Roshni", "Ruchi", "Rukmini", "Rupal", "Saachi", "Saanvi", "Sadhvi", "Sakshi", "Samaira", "Samiksha",
            "Sana", "Sanaya", "Sanjana", "Sanskriti", "Sanya", "Sarika", "Sejal", "Shailaja", "Shanaya", "Shanti",
            "Shivangi", "Shreya", "Shrishti", "Shruti", "Shweta", "Simran", "Sita", "Sneha", "Sonal", "Sonali",
            "Sonam", "Srishti", "Stuti", "Suhana", "Sumati", "Sunita", "Surbhi", "Swara", "Swati", "Tanvi",
            "Tanya", "Tara", "Trisha", "Tulsi", "Twinkle", "Ujjwala", "Urvi", "Vaani", "Vaidehi", "Vani",
            "Vanshika", "Varsha", "Vedika", "Vidhi", "Vidya", "Vrinda", "Yamini", "Yashasvi", "Yashika", "Yashvi",
            "Yasti", "Zara", "Aadya", "Aanya", "Aarushi", "Aashi", "Aayat", "Adhira", "Adya",
            "Akanksha", "Akshita", "Alina", "Amaira", "Amoli", "Anagha", "Anahita", "Anamika", "Ananya", "Anaya",
            "Anika", "Anisha", "Anjali", "Anvi", "Anya", "Aparajita", "Archita", "Aruna", "Aryahi", "Asmita",
            "Avani", "Avanti", "Ayana", "Bageshri", "Bansari", "Barsha", "Bela", "Bhadra", "Bhavika", "Bhoomi",
            "Bhumika", "Bipasha", "Chandni", "Charvi", "Chhaya", "Daksha", "Damini", "Darshana", "Deeksha", "Deepali",
            "Devanshi", "Dhara", "Dhatri", "Dhwani", "Dia", "Diksha", "Divija", "Divyanshi", "Drishti", "Ela",
            "Eshana", "Falguni", "Gargi", "Gaurangi", "Gayatri", "Gunjan", "Hansika", "Harinya", "Harsha", "Harshita",
            "Heer", "Hetal", "Himadri", "Hiral", "Iha", "Iksha", "Ila", "Indira", "Ira", "Ishani",
            "Ishita", "Jagriti", "Jahnvi", "Jaya", "Jhanvi", "Jigyasa", "Jivika", "Kajal", "Kalpana", "Kamakshi",
            "Kanak", "Kanika", "Kashvi", "Kavisha", "Khushi", "Kiara", "Kirti", "Komal", "Krishika", "Kriti",
            "Kritika", "Krithika", "Kyra", "Lakshita", "Lavanya", "Lipika", "Madhavi", "Mahika", "Maitreyi", "Manjari",
            "Manvi", "Manyata", "Meenakshi", "Meghana", "Misha", "Mitali", "Mohini", "Moksha", "Mridula", "Mrunal",
            "Muskan", "Myra", "Naina", "Nakshatra", "Nandini", "Navya", "Neelam", "Nehal", "Nidhi", "Niharika",
            "Nikita", "Nimisha", "Nirali", "Nisha", "Nishita", "Nitya", "Ojasvi", "Palak", "Pari", "Parineeti",
            "Pihu", "Pooja", "Pragati", "Pragya", "Prachi", "Pratiksha", "Preeti", "Prisha", "Priya", "Priyal",
            "Priyanka", "Radhika", "Ragini", "Rajvi", "Rashi", "Rati", "Reeva", "Rehnuma", "Ria", "Riddhi",
            "Rishika", "Ritika", "Riya", "Roshni", "Ruchi", "Rukmini", "Rupal", "Saachi", "Saanvi", "Sadhvi",
            "Sakshi", "Samaira", "Samiksha", "Sana", "Sanaya", "Sanjana", "Sanskriti", "Sanya", "Sarika", "Sejal",
            "Shailaja", "Shanaya", "Shanti", "Shivangi", "Shreya", "Shrishti", "Shruti", "Shweta", "Simran", "Sita",
            "Sneha", "Sonal", "Sonali", "Sonam", "Srishti", "Stuti", "Suhana", "Sumati", "Sunita", "Surbhi",
            "Swara", "Swati", "Tanvi", "Tanya", "Tara", "Trisha", "Tulsi", "Twinkle", "Ujjwala", "Urvi",
            "Vaani", "Vaidehi", "Vani", "Vanshika", "Varsha", "Vedika", "Vidhi", "Vidya", "Vrinda", "Yamini",
            "Yashasvi", "Yashika", "Yashvi", "Yasti", "Zara"
    );

}